jQuery(document).ready(function(){
	jQuery(".multiplechoice").hide();
	jQuery(".essay").hide();
	jQuery(".identification").hide();
	var i = 1;
	
	jQuery('#mjbAdd').click(function(){
		var item = jQuery('.elements input[name="element"]:checked').val();
		html = "<div id='mjbItemQuestion" + i + "'>";
		if(item == "ide"){
			html += "<div class='mjbItemIde" + i + "'>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Ide-"+ i +"'>Question</label>";
			html += "<input type='text' name='mjbItemquestion_Ide-" + i + "' id='mjbItemquestion_Ide-" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='col-2'>";
			html += "<label for='mjbItemquestion_Ide-a"+ i +"'>Answer</label>";
			html += "<input type='text' name='mjbItemquestion_Ide-a" + i + "' id='mjbItemquestion_Ide-a" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='col-2'>";
			html += "<label for='mjbItemquestion_Ide-s" + i + "'>Score</label>";
			html += "<input type='number' name='mjbItemquestion_Ide-s" + i + "' id='mjbItemquestion_Ide-s" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='clr'></div>";
			html += "</div>";
			jQuery(html).appendTo(".containerContent");
		}else if(item == "multi"){
			html += "<div class='mjbItemMul" + i + "'>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Mul-"+ i +"'>Question</label>";
			html += "<input type='text' name='mjbItemquestion_Mul-" + i + "' id='mjbItemquestion_Mul-" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='col-2'>";
			html += "<label for='mjbItemquestion_Mul-a" + i + "'>Answer</label>";
			html += "<input type='text' name='mjbItemquestion_Mul-a" + i + "' id='mjbItemquestion_Mul-a" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='col-2'>";
			html += "<label for='mjbItemquestion_Mul-s" + i + "'>Score</label>";
			html += "<input type='number' name='mjbItemquestion_Mul-s" + i + "' id='mjbItemquestion_Mul-s" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='clr'></div>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Mul-c"+ i +"1'>Choice 1</label>";
			html += "<input type='text' name='mjbItemquestion_Mul-c" + i + "-1' id='mjbItemquestion_Mul-c" + i + "1' value=''/>";
			html += "</div>";
			html += "<div class='clr'></div>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Mul-c"+ i +"2'>Choice 2</label>";
			html += "<input type='text' name='mjbItemquestion_Mul-c" + i + "-2' id='mjbItemquestion_Mul-c" + i + "2' value=''/>";
			html += "</div>";
			html += "<div class='clr'></div>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Mul-c"+ i +"3'>Choice 3</label>";
			html += "<input type='text' name='mjbItemquestion_Mul-c" + i + "-3' id='mjbItemquestion_Mul-c" + i + "3' value=''/>";
			html += "</div>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Mul-c"+ i +"4'>Choice 4</label>";
			html += "<input type='text' name='mjbItemquestion_Mul-c" + i + "-4' id='mjbItemquestion_Mul-c" + i + "4' value=''/>";
			html += "</div>";
			html += "<div class='clr'></div>";
			html += "<div class='clr'></div>";
			html += "</div>";
			jQuery(html).appendTo(".containerContent");
		}else if(item == "es"){
			html += "<div class='mjbItem" + i + "'>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Es-"+ i +"'>Question</label>";
			html += "<input type='text' name='mjbItemquestion_Es-" + i + "' id='mjbItemquestion_Es-" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='col-2'>";
			html += "<label for='mjbItemquestion_Es-a"+ i +"'>Keywords</label>";
			html += "<input type='text' name='mjbItemquestion_Es-a" + i + "' id='mjbItemquestion_Es-a" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='col-2'>";
			html += "<label for='mjbItemquestion_Es-s" + i + "'>Score</label>";
			html += "<input type='number' name='mjbItemquestion_Es-s" + i + "' id='mjbItemquestion_Es-s" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='clr'></div>";
			html += "</div>";
			jQuery(html).appendTo(".containerContent");
		}else if(item == "sb"){
			html += "<div class='mjbItem" + i + "'>";
			html += "<div class='col-8'>";
			html += "<label for='mjbItemquestion_Sb-"+ i +"'>No. of Points to Continue</label>";
			html += "<input type='text' name='mjbItemquestion_Sb-" + i + "' id='mjbItemquestion_Sb-" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='col-2'>";
			html += "<label for='mjbItemquestion_Sb-a"+ i +"'>Button Text</label>";
			html += "<input type='text' name=mjbItemquestion_Sb-a" + i + "' id='mjbItemquestion_Sb-a" + i + "' value=''/>";
			html += "</div>";
			html += "<div class='clr'></div>";
			html += "</div>";
			jQuery(html).appendTo(".containerContent");
		}
		html += "</div>";
		i++;
	});
});
